apiVersion: v2
name: common-server
description: A Helm chart for Kubernetes

dependencies:
- name: redis
  condition: redis.enabled
  repository: https://charts.bitnami.com/bitnami
  version: 14.8.11
- name: redis-debian
  condition: redis-debian.enabled
  repository: https://charts.bitnami.com/bitnami
  version: 14.8.11
- name: oss
  condition: oss.enabled
  repository: https://charts.bitnami.com/bitnami
  version: 7.2.0
# - name: oss-gateway
#   condition: oss-gateway.enabled
#   repository: https://charts.bitnami.com/bitnami
#   version: 7.2.1
- name: oss-gateway
  condition: oss-gateway.enabled
  repository: https://charts.bitnami.com/bitnamis
  version: 10.1.14
- name: postgresql
  condition: postgresql.enabled
  repository: https://charts.bitnami.com/bitnami
  version: 10.10.1
- name: license-client
  condition: license-client.enabled
  repository: https://hub.fano.ai/chartrepo/fanolabs
  version: 0.0.0-master
- name: fano-license-control
  condition: fano-license-control.enabled
  repository: https://hub.fano.ai/chartrepo/fanolabs
  version: 0.0.0-master
- name: mysql
  condition: mysql.enabled
  repository: https://charts.bitnami.com/bitnami
  version: 8.8.21
- name: nats
  condition: nats.enabled
  repository: http://github.com/nats-io/k8s
  version: 0.10.0
- name: db-backup
  condition: db-backup.enabled
  repository: https://hub.fano.ai/chartrepo/fanolabs
  version: 0.0.0-master

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"
