{{- if .Values.Secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: fano-common-secret
type: Opaque
data:
  oss_secretkey: {{ .Values.Secret.oss_secretkey | b64enc | quote }}
  rdbms_password: {{ .Values.Secret.rdbms_password | b64enc | quote }}
  keycloak_admin_password: {{ .Values.Secret.keycloak_admin_password | b64enc | quote }}
  cloud_app_keycloak_client_secret: {{ .Values.Secret.cloud_app_keycloak_client_secret | b64enc | quote }}
{{ end }}