{{- if .Values.fanoSecretHK.enabled }}
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodWIuZmFuby5haSI6eyJ1c2VybmFtZSI6InJvYm90I2Zhbm8tazhzIiwicGFzc3dvcmQiOiJGQW5vTGFiczIwMjEjOCIsImF1dGgiOiJjbTlpYjNRalptRnVieTFyT0hNNlJrRnViMHhoWW5NeU1ESXhJemc9In19fQ==
kind: Secret
metadata:
  name: fano-secret-hk
type: kubernetes.io/dockerconfigjson
{{ end }}