apiVersion: v1
kind: ConfigMap
metadata:
  name: appdatapanelconfig
  labels:
    {{- include "fanolabs.labels" . | nindent 4 }}
data:
  default.conf: |-
    server {
      listen 8080;
      # listen 8443 ssl;
      # server_name 127.0.0.1;
      # ssl_certificate /etc/nginx/certs/server-cert.pem;
      # ssl_certificate_key /etc/nginx/certs/server-key.pem;

      ssl_session_cache shared:SSL:1m;
      ssl_session_timeout 5m;
      ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
      ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
      ssl_prefer_server_ciphers on;

      client_max_body_size 1024m;
      client_body_buffer_size 10m;
      client_header_buffer_size 10m;
      large_client_header_buffers 4 10240k;
      

      # datapanel healthz
      location /app/datapanel/healthz {
        return 200;
      }
      
      # datapanel backend
      location /app/datapanel/apis/ {
        proxy_read_timeout 900;
        proxy_pass {{ .Values.configmap.VUE_APP_DATAPANEL_PORTAL_HOST_URL | quote }};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #more_set_headers Access-Control-Allow-Origin *.webflow.io;
        # add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Credentials' 'true';
        # add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type,Accept,Origin,User-Agent,DNT,Cache-Control,X-Mx-ReqToken,X-Requested-With';
        # add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS';
        # add_header X-Frame-Options ALLOWALL;
        add_header X-DNS-Prefetch-Control off;
        add_header Strict-Transport-Security "max-age=15552000; includeSubDomains";
        add_header X-Download-Options noopen;
        add_header X-Content-Type-Options nosniff;
        add_header Content-Security-Policy "font-src 'self' data:";
        add_header X-XSS-Protection "1; mode=block";
        add_header Cache-Control "no-cache";
        add_header Referrer-Policy "strict-origin";
        add_header X-Real-IP $remote_addr;
        add_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }

      # datapanel static
      location ~ /app/datapanel/static/.+$ {
        root /usr/share/nginx/html;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #more_set_headers Access-Control-Allow-Origin *.webflow.io;
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Credentials' 'true';
        add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type,Accept,Origin,User-Agent,DNT,Cache-Control,X-Mx-ReqToken,X-Requested-With';
        add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS';
        add_header X-Frame-Options ALLOWALL;
        add_header X-DNS-Prefetch-Control off;
        add_header Strict-Transport-Security "max-age=15552000; includeSubDomains";
        add_header X-Download-Options noopen;
        add_header X-Content-Type-Options nosniff;
        add_header Content-Security-Policy "font-src 'self' data:";
        add_header X-XSS-Protection "1; mode=block";
        add_header Cache-Control "no-cache";
        add_header Referrer-Policy "strict-origin";
      }

      # datapanel static
      location /app/datapanel/static {
          return 404;
      }

      # datapanel frontend
      location /app/datapanel {
        alias /usr/share/nginx/html/app/datapanel; 
        index index.html; 
        try_files $uri /index.html last;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #more_set_headers Access-Control-Allow-Origin *.webflow.io;
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Credentials' 'true';
        add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type,Accept,Origin,User-Agent,DNT,Cache-Control,X-Mx-ReqToken,X-Requested-With';
        add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS';
        add_header X-Frame-Options ALLOWALL;
        add_header X-DNS-Prefetch-Control off;
        add_header Strict-Transport-Security "max-age=15552000; includeSubDomains";
        add_header X-Download-Options noopen;
        add_header X-Content-Type-Options nosniff;
        add_header Content-Security-Policy "font-src 'self' data:";
        add_header X-XSS-Protection "1; mode=block";
        add_header Cache-Control "no-cache";
        add_header Referrer-Policy "strict-origin";
      }
    }
  config.js: |-
    const keycloakUrl = {{ .Values.configmap.VUE_APP_DATAPANEL_PORTAL_KEYCLOAK_URL | quote }};
    const keycloakDefaultRealm = {{ .Values.configmap.VUE_APP_DATAPANEL_PORTAL_KEYCLOAK_DEFAULT_REALM | quote }};
    const keycloakPortalClientId = {{ .Values.configmap.VUE_APP_DATAPANEL_PORTAL_KEYCLOAK_PORTAL_CLIENT_ID | quote }};
    const realmFromHostNameLength = {{ .Values.configmap.VUE_APP_DATAPANEL_PORTAL_REALM_FROM_HOST_NAME_LENGTH }};
    const portalUrl = {{ .Values.configmap.VUE_APP_PORTAL_URL | quote }};
    const datapanelServerId = {{ .Values.configmap.VUE_APP_DATAPANEL_PORTAL_SERVER_ID | quote  }};
    const keycloakUpdateTokenMinValidity = {{ .Values.configmap.VUE_APP_DATAPANEL_PORTAL_KEYCLOAK_UPDATE_TOKEN_MIN_VALIDITY }};
    const msgDuration = {{ .Values.configmap.VUE_APP_DATAPANEL_PORTAL_MSG_DURATION }};
    const disableNodeClickDuration = {{ .Values.configmap.VUE_APP_DATAPANEL_PORTAL_DISABLE_NODE_CLICK_DURATION }};
    const maxErrorMsgLength = {{ .Values.configmap.VUE_APP_DATAPANEL_PORTAL_MAX_ERROR_MSG_LENGTH }};
    const viewDataMaxCount = 1000;
    const dataSourceSqlScriptMaxLength = 5000;
    const storeProcedureSqlScriptMaxLength = 5000;
    const addDashBoardRole = 'dashboard-add';
    const copyDashBoardRole = 'dashboard-copy';
    const deleteDashBoardRole = 'dashboard-delete';
    const editDashBoardRole = 'dashboard-edit';
    const exportDashBoardRole = 'dashboard-export';
    const importDashBoardRole = 'dashboard-import';
    const shareDashBoardRole = 'dashboard-share';
    const exportDataDashBoardRole = 'dashboard-export-data';
    const viewDashBoardRole = 'dashboard-view';
    const addDataSetRole = 'dataset-add';
    const copyDataSetRole = 'dataset-copy';
    const deleteDataSetRole = 'dataset-delete';
    const editDataSetRole = 'dataset-edit';
    const exportDataSetRole = 'dataset-export';
    const exportDataDataSetRole = 'dataset-export-data';
    const importDataSetRole = 'dataset-import';
    const shareDataSetRole = 'dataset-share';
    const viewDataSetRole = 'dataset-view';
    const addDataSourceRole = 'datasource-add';
    const deleteDataSourceRole = 'datasource-delete';
    const editDataSourceRole = 'datasource-edit';
    const exportDataSourceRole = 'datasource-export';
    const importDataSourceRole = 'datasource-import';
    const viewDataSourceRole = 'datasource-view';
    const addDataViewRole = 'dataview-add';
    const copyDataViewRole = 'dataview-copy';
    const deleteDataViewRole = 'dataview-delete';
    const editDataViewRole = 'dataview-edit';
    const exportDataViewRole = 'dataview-export';
    const importDataViewRole = 'dataview-import';
    const shareDataViewRole = 'dataview-share';
    const exportDataDataViewRole = 'dataview-export-data';
    const viewDataViewRole = 'dataview-view';
    const addStoreProcedureRole = 'storeprocedure-add';
    const deleteStoreProcedureRole = 'storeprocedure-delete';
    const editStoreProcedureRole = 'storeprocedure-edit';
    const exportStoreProcedureRole = 'storeprocedure-export';
    const importStoreProcedureRole = 'storeprocedure-import';
    const viewStoreProcedureRole = 'storeprocedure-view';
    const ownershipTransferRole = 'ownership-transfer';