{
    "keycloakUrl": "https://chluat.fano.ai/iam",
    "keycloakDefaultRealm": "fanolabs",
    "keycloakPortalClientId": "Intent",
    "realmFromHostNameLength": 100,
    "portalUrl": "chluat.fano.ai/app/portal",
    "portalCrudPrefixPath": "/portal-crud",
    "intentServerId": "fano_app_portal_intent",
    "keycloakUpdateTokenMinValidity": 60,
    "msgDuration": 10000,
    "maxUploadSize": 10,
    "wordCloudDataMinTimes": 1,
    "wordCloudDataMaxTimes": 2000,
    "wordCloudDataMinLength": 1,
    "wordCloudDataMaxLength": 10,
    "wordCloudDataTop": 100,
    "clusterAutoRefreshInterval": 60000,
    "addBuiltInEntityRole": "built-in-entity-add",
    "deleteBuiltInEntityRole": "built-in-entity-delete",
    "editBuiltInEntityRole": "built-in-entity-edit",
    "exportBuiltInEntityRole": "built-in-entity-export",
    "importBuiltInEntityRole": "built-in-entity-import",
    "publishBuiltInEntityRole": "built-in-entity-publish",
    "viewBuiltInEntityRole": "built-in-entity-view",
    "addClusterRole": "cluster-add",
    "archiveClusterRole": "cluster-archive",
    "cancelClusterRole": "cluster-cancel",
    "deleteClusterRole": "cluster-delete",
    "editClusterRole": "cluster-edit",
    "viewClusterRole": "cluster-view",
    "addIntentRole": "intent-add",
    "deleteIntentRole": "intent-delete",
    "editIntentRole": "intent-edit",
    "exportIntentRole": "intent-export",
    "importIntentRole": "intent-import",
    "viewIntentRole": "intent-view",
    "addModelRole": "model-add",
    "copyModelRole": "model-copy",
    "deleteModelRole": "model-delete",
    "editModelRole": "model-edit",
    "shareModelRole": "model-share",
    "importModelRole": "model-import",
    "viewModelRole": "model-view",
    "addTrainingSetRole": "trainingset-add",
    "deleteTrainingSetRole": "trainingset-delete",
    "editTrainingSetRole": "trainingset-edit",
    "importTrainingSetRole": "trainingset-import",
    "viewTrainingSetRole": "trainingset-view",
    "addTrainingTaskRole": "trainingtask-add",
    "copyTrainingTaskRole": "trainingtask-copy",
    "downloadTrainingTaskRole": "trainingtask-download",
    "viewTrainingTaskRole": "trainingtask-view",
    "viewRegressionTestRole": "regressiontest-view",
    "ownershipTransferRole": "ownership-transfer",
    "classifierTypes": [
        "DistilBERT",
        "QDistilBERT",
        "TinyBERT",
        "BERT-DCL"
    ]
}