{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $release_name := .Release.Name }}
{{- $fullName := include "db-backup.name" . -}}

{{- range  $job := .Values.jobs }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $job.name }}-envsecret"
  labels:
    chart: "{{ $chart_name }}-{{ $chart_version }}"
type: Opaque
data:
{{- range $key, $value := $job.envSecret }}
   {{ $key }}: {{ $value| b64enc | quote }}
{{- end }}

{{- end }}
