apiVersion: v2
name: fano-callinter
description: A Helm chart for Kubernetes

dependencies:
- name: fano-callinter-web
  condition: fano-callinter-web.enabled
  version: 0.1.0
- name: fano-callinter-analyze-worker
  condition: fano-callinter-analyze-worker.enabled
  version: 0.1.0
- name: fano-callinter-crud
  condition: fano-callinter-crud.enabled
  version: 0.1.0
- name: fano-callinter-quality-check-worker
  condition: fano-callinter-quality-check-worker.enabled
  version: 0.1.0
- name: fano-callinter-speech-adapter
  condition: fano-callinter-speech-adapter.enabled
  version: 0.1.0
- name: fano-callinter-download-worker
  condition: fano-callinter-download-worker.enabled
  version: 0.1.0
- name: fano-callinter-speech-post-processing
  condition: fano-callinter-speech-post-processing.enabled
  version: 0.1.0
- name: fano-callinter-sanitising
  condition: fano-callinter-sanitising.enabled
  version: 0.1.0
- name: fano-callinter-convert-worker
  condition: fano-callinter-convert-worker.enabled
  version: 0.1.0 
  
# - name: fano-voiceprint
#   condition: fano-voiceprint.enabled
#   version: 0.1.0


# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"
