apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-license-control-service
spec:
  selector:
    service: {{ .Release.Name }}-license-control
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
