global:
  imageRegistry: 'hub.fano.ai'
  imagePullSecrets:
    - fano-secret-hk
  existingClaim: 'hkpf-netwatch-uat'
  nodeAffinityPreset:
    type: ""
    key: ""
    values:
      - test
  hostAliases:
    enabled: true
    values:
      - ip: "192.168.174.20"
        hostnames:
        - "netwatch-uat.fano.ai"

############################################################################################################################
##    service: fano-datapanel-web                                                                                         ##
############################################################################################################################
fano-datapanel-web:
  enabled: true
  replicaCount: 1

  image:
    repository: fanolabs/fano-datapanel-web
    pullPolicy: IfNotPresent
  configmap:
    VUE_APP_DATAPANEL_PORTAL_KEYCLOAK_URL: "https://netwatch-uat.fano.ai/iam"
    VUE_APP_DATAPANEL_PORTAL_KEYCLOAK_DEFAULT_REALM: "fanolabs"
    VUE_APP_DATAPANEL_PORTAL_KEYCLOAK_PORTAL_CLIENT_ID: "DataPanel"
    VUE_APP_DATAPANEL_PORTAL_KEYCLOAK_UPDATETOKEN_MINVALIDITY: "60"
    VUE_APP_DATAPANEL_PORTAL_REALM_FROM_HOST_NAME_LENGTH: "100"
    VUE_APP_DATAPANEL_PORTAL_HOST_URL: "http://fano-datapanel-crud:8080/"
    VUE_APP_CLOUD_PORTAL_HOST_URL: "http://fano-portal-crud:8080/"
    VUE_APP_PORTAL_URL: "netwatch-uat.fano.ai/app/portal"
    VUE_APP_DATAPANEL_PORTAL_SERVER_ID: "fano_app_portal_datapanel"
    VUE_APP_DATAPANEL_PORTAL_KEYCLOAK_UPDATE_TOKEN_MIN_VALIDITY: "60"
    VUE_APP_DATAPANEL_PORTAL_MSG_DURATION: "10000"
    VUE_APP_DATAPANEL_PORTAL_DISABLE_NODE_CLICK_DURATION: "2000"
    VUE_APP_DATAPANEL_PORTAL_MAX_ERROR_MSG_LENGTH: "20"
    PORTAL_SERVER_URL: "netwatch-uat.fano.ai"
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80


############################################################################################################################
##    service: fano-datapanel-crud                                                                                        ##
############################################################################################################################
fano-datapanel-crud:
  enabled: true
  replicaCount: 1
  image:
    repository: fanolabs/fano-datapanel-crud
    pullPolicy: IfNotPresent
  env:
    TZ: "Asia/Hong_Kong"
    NODE_TLS_REJECT_UNAUTHORIZED: "0"
    NODE_OPTIONS: "--max-http-header-size=81920"
    MINIO_ENDPOINT: "fano-common-oss"
    MINIO_PORT: "9000"
    MINIO_BUCKET: "hkpf-netwatch-uat"
    PORTAL_RDBMS_DEFAULT_DATASOURCE_CONN_NAME: "FANODB"
    PORTAL_RDMBS_CONNECTION_TYPE: "sql-login"
    PORTAL_RDBMS_ENGINE: "mysql"
    PORTAL_RDBMS_HOST: "fano-common-mysql"
    PORTAL_RDBMS_PORT: "3306"
    PORTAL_RDBMS_DB: "netwatchuat"
    PORTAL_RDBMS_USER: "netwatchuatusr"
    PORTAL_RDMBS_REQUIRE_ENCRYPT: "false"
    PORTAL_RDMBS_REQUIRE_SERCURE_TRANSPORT: "false"
    PORTAL_DATAPANEL_NODE_ENV: "production"
    PORTAL_DATAPANEL_PORT: "8080"
    PORTAL_RDMBS_POOL_MIN: "10"
    PORTAL_RDMBS_POOL_MAX: "500"
    PORTAL_RDBMS_TIMEZONE: "Asia/Hong_Kong"
    PORTAL_RDBMS_UTC_OFFSET: "+08:00"
    PORTAL_DATAPANEL_CLOUD_SERVER_URL: "http://fano-portal-crud:8080/fano/cloud"
    PORTAL_DATAPANEL_SYNC_DATASET_INTERVAL_MINUTES: "1"
    PORTAL_DATAPANEL_CLOUD_SERVER_DOMAIN: "netwatch-uat.fano.ai/app/portal"
    PORTAL_DATAPANEL_DOMAIN: "netwatch-uat.fano.ai/app/datapanel"
    PORTAL_DATAPANEL_KEYCLOAK_DEFAULT_REALM: "fanolabs"
    PORTAL_DATAPANEL_DATASET_LIMIT_SIZE: "1000000"
    PORTAL_DATAPANEL_DATASET_EXPORT_SIZE_PER_TIME: "100000"
    PORTAL_DATAPANEL_DATASET_EXECUTE_SQL_TIMEOUT: "30000"
    PORTAL_DATAPANEL_DATASOURCE_DATA_PREVIEW_LIMIT_SIZE: "100"
    MINIO_ACCESS_KEY: "admin"
    MINIO_FORCE_REGION: "false"   #Set to true if using Dell s3 storage.
    PORTAL_RDBMS_DOMAIN: ""       #Set to support MSSQL Windows Authentication
    SSL_ENABLE: ""                #Set to true if enable https service  
    SSL_KEY: ""                   #ssl_key file path         
    SSL_CRT: ""                   #ssl_cert file path
    NATS_SSL_ENABLE: ""           #Set to true if enable nats https service
    NATS_SSL_CA: ""               #nats_ssl_ca file path
    NATS_SSL_KEY: ""              #nats_ssl_key file path
    NATS_SSL_CRT: ""              #nats_ssl_cert file path
  envSecret:
    MINIO_SECRET_KEY: "oss_secretkey"
    PORTAL_RDBMS_PWD: "rdbms_password"
  localVolume:
    enabled: false
    hostPath: /opt/fano/data/hkpf-netwatch-uat/files
  service:
    type: ClusterIP
    port: 8080
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: "nginx"
    hosts:
      - host: netwatch-uat.fano.ai
        paths:
        - /app/datapanel
  command:
    - '/bin/sh'
  commandArgs:
    - '-c'
    - '/app/run.sh'
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 128Mi

############################################################################################################################
##    service: fano-datapanel-job                                                                                         ##
############################################################################################################################
fano-datapanel-job:
  enabled: true
  replicaCount: 1
  image:
    repository: fanolabs/fano-datapanel-crud
    pullPolicy: IfNotPresent
  initData:
    enabled: true
    env:
      TZ: "Asia/Hong_Kong"
      RDBMS_DEFAULT_DATASOURCE_CONN_NAME: "FANODB"
      RDMBS_CONNECTION_TYPE: "sql-login"
      RDBMS_ENGINE: "mysql"
      RDBMS_HOST: "fano-common-mysql"
      RDBMS_PORT: "3306"
      PORTAL_RDMBS_REQUIRE_SERCURE_TRANSPORT: "false"
      RDBMS_DB: "netwatchuat"
      RDBMS_USER: "netwatchuatusr"
      RDMBS_POOL_MIN: "10"
      RDMBS_POOL_MAX: "500"
      RDBMS_DOMAIN: ""       #Set to support MSSQL Windows Authentication
    envSecret:
      RDBMS_PWD: "rdbms_password"
    image:
      repository: fanolabs/fano-portal-init-data
      pullPolicy: IfNotPresent
    shellImage:
      repository: fanolabs/fano-dia-init-data
      pullPolicy: IfNotPresent
  env:
    TZ: "Asia/Hong_Kong"
    NODE_TLS_REJECT_UNAUTHORIZED: "0"
    NODE_OPTIONS: "--max-http-header-size=81920"
    MINIO_ENDPOINT: "fano-common-oss"
    MINIO_PORT: "9000"
    MINIO_BUCKET: "hkpf-netwatch-uat"
    PORTAL_RDBMS_DEFAULT_DATASOURCE_CONN_NAME: "FANODB"
    PORTAL_RDMBS_CONNECTION_TYPE: "sql-login"
    PORTAL_RDBMS_ENGINE: "mysql"
    PORTAL_RDBMS_HOST: "fano-common-mysql"
    PORTAL_RDBMS_PORT: "3306"
    PORTAL_RDBMS_DB: "netwatchuat"
    PORTAL_RDBMS_USER: "netwatchuatusr"
    PORTAL_RDMBS_REQUIRE_ENCRYPT: "false"
    PORTAL_RDMBS_REQUIRE_SERCURE_TRANSPORT: "false"
    PORTAL_DATAPANEL_NODE_ENV: "production"
    PORTAL_DATAPANEL_PORT: "8080"
    PORTAL_RDMBS_POOL_MIN: "10"
    PORTAL_RDMBS_POOL_MAX: "500"
    PORTAL_DATAPANEL_CLOUD_SERVER_URL: "http://fano-portal-crud:8080/fano/cloud"
    PORTAL_DATAPANEL_SYNC_DATASET_INTERVAL_MINUTES: "1"
    PORTAL_DATAPANEL_CLOUD_SERVER_DOMAIN: "netwatch-uat.fano.ai/app/portal"
    PORTAL_DATAPANEL_DOMAIN: "netwatch-uat.fano.ai/app/datapanel"
    PORTAL_DATAPANEL_KEYCLOAK_DEFAULT_REALM: "fanolabs"
    PORTAL_DATAPANEL_DATASET_LIMIT_SIZE: "1000000"
    PORTAL_DATAPANEL_DATASET_EXPORT_SIZE_PER_TIME: "100000"
    MINIO_ACCESS_KEY: "admin"
    PORTAL_RDBMS_DOMAIN: "" #Set to support MSSQL Windows Authentication

  envSecret:
    MINIO_SECRET_KEY: "oss_secretkey"
    PORTAL_RDBMS_PWD: "rdbms_password"

  localVolume:
    enabled: false
    hostPath: /opt/fano/data/hkpf-netwatch-uat/files

  service:
    type: ClusterIP
    port: 8080

  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: "nginx"
    hosts:
      - host: tts-xxx.fano.ai
        paths:
        - /

  commandjob:
    - '/bin/sh'

  commandArgsjob:
    - '-c'
    - '/app/run.sh job'

  resources:
    limits:
      cpu: 2000m
      memory: 4096Mi
    requests:
      cpu: 100m
      memory: 128Mi
